### ISSUE TITLE
Details about evaluation

### ISSUE THREAD

**Issue by Qjizhi** [lez-s/StereoDiffusion#7]
Hi, thanks for your great work. I am confused about the lips. Are you using Vgg net or Alex net?

**Comment by lez-s** [comment]
hi , I used 'squeeze' type.
here is the [url](https://lightning.ai/docs/torchmetrics/stable/image/learned_perceptual_image_patch_similarity.html) of lpips module I used.

**Comment by Qjizhi** [comment]
> hi , I used 'squeeze' type. here is the [url](https://lightning.ai/docs/torchmetrics/stable/image/learned_perceptual_image_patch_similarity.html) of lpips module I used.

Thanks for your verification!
