### ISSUE TITLE
Regarding the issue of DRMNet

### ISSUE THREAD

**Issue by ScuLancer** [lez-s/StereoDiffusion#8]
May I ask if you have successfully reproduced DRMNet? I noticed that you left an issue under DRMNet and I haven't been working on it. This is my error message:
Critical Dr.Jit compiler failure: jit_optix_check(): API error 7990 (OPTIX_ERROR_INTERNAL_ERROR): "Internal error" in /project/src/render/optixdenoiser.cpp:38.
Aborted (core dumped)

**Comment by lez-s** [comment]
no, it doesn't work, and I gave up work on their code. you can try [DPI](https://github.com/LinjieLyu/DPI), their code works.
